import Byc from './byc.png'
import Frame1 from './Frame1.png'
import Frame2 from './Frame2.png'
import Frame3 from './Frame3.png'
import Frame4 from './Frame4.png'
import Frame5 from './Frame5.png'
import Frame6 from './Frame6.png'
import Frame7 from './Frame7.png'
import Frame8 from './Frame8.png'
import Frame9 from './Frame9.png'
import Card1 from './Card1.png'
import Card2 from './Card2.png'
import Card3 from './Card3.png'
import Frame10 from './Frame10.png'
import Frame11 from './Frame11.png'
import Frame12 from './Frame12.png'
import Frame13 from './Frame13.png'
import Frame14 from './Frame14.png'
import Frame15 from './Frame15.png'
import Frame16 from './Frame16.png'
import Frame17 from './Frame17.png'
import Frame19 from './Frame19.png'
import Awards from './Awards.png'
import Image from './Image.png'
import Mcard from './Mcard.png'
import Paypal from './Paypal.png'
import Visa from './Visa.png'
import Icon1 from './Icon1.png'
import Icon2 from './Icon2.png'
import Icon3 from './Icon3.png'
import Icon4 from './Icon4.png'
import Rectangle from './Rectangle.png'
import Location from './Location.png'
import Call from './Call.png'
import Email from './Email.png'

export {Byc, Frame1, Frame2, Frame3, Frame4, Frame5, Frame6, Frame7, Frame8, Frame9,
     Frame14, Frame15, Frame16,Rectangle, Location, Call, Email,Frame19,
Card1, Card2, Card3, Frame10, Frame11, Frame12,Frame13, Image, Mcard, Paypal, Visa, Icon1, Icon2, Icon3, Icon4, Awards, Frame17
}